// <auto-generated />
using System;
using Delyport.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Delyport.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260602221607_HU_Conductores")]
    partial class HU_Conductores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Delyport.Api.Models.Entities.AsignacionServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.ToTable("AsignacionesServicio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoServicio = "SRV-001",
                            ConductorId = 1,
                            Descripcion = "Ruta de entrega #1",
                            Destino = "Santa Anita",
                            Estado = 0,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6053),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 150.0m
                        },
                        new
                        {
                            Id = 2,
                            CodigoServicio = "SRV-002",
                            ConductorId = 2,
                            Descripcion = "Ruta de entrega #2",
                            Destino = "Comas",
                            Estado = 1,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6063),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 160.0m
                        },
                        new
                        {
                            Id = 3,
                            CodigoServicio = "SRV-003",
                            ConductorId = 3,
                            Descripcion = "Ruta de entrega #3",
                            Destino = "El Agustino",
                            Estado = 3,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6066),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 170.0m
                        },
                        new
                        {
                            Id = 4,
                            CodigoServicio = "SRV-004",
                            ConductorId = 4,
                            Descripcion = "Ruta de entrega #4",
                            Destino = "Los Olivos",
                            Estado = 3,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6069),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 180.0m
                        },
                        new
                        {
                            Id = 5,
                            CodigoServicio = "SRV-005",
                            ConductorId = 1,
                            Descripcion = "Ruta de entrega #5",
                            Destino = "Miraflores",
                            Estado = 0,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6071),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 190.0m
                        },
                        new
                        {
                            Id = 6,
                            CodigoServicio = "SRV-006",
                            ConductorId = 2,
                            Descripcion = "Ruta de entrega #6",
                            Destino = "Santa Anita",
                            Estado = 2,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6073),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 200.0m
                        },
                        new
                        {
                            Id = 7,
                            CodigoServicio = "SRV-007",
                            ConductorId = 3,
                            Descripcion = "Ruta de entrega #7",
                            Destino = "Comas",
                            Estado = 3,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6075),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 210.0m
                        },
                        new
                        {
                            Id = 8,
                            CodigoServicio = "SRV-008",
                            ConductorId = 4,
                            Descripcion = "Ruta de entrega #8",
                            Destino = "El Agustino",
                            Estado = 1,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6077),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 220.0m
                        },
                        new
                        {
                            Id = 9,
                            CodigoServicio = "SRV-009",
                            ConductorId = 1,
                            Descripcion = "Ruta de entrega #9",
                            Destino = "Los Olivos",
                            Estado = 0,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6079),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 230.0m
                        },
                        new
                        {
                            Id = 10,
                            CodigoServicio = "SRV-0010",
                            ConductorId = 2,
                            Descripcion = "Ruta de entrega #10",
                            Destino = "Miraflores",
                            Estado = 3,
                            FechaAsignacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6084),
                            Origen = "Almacén Central Santa Anita",
                            Tarifa = 240.0m
                        });
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlacaVehiculo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conductores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreCompleto = "Juan Pérez",
                            PlacaVehiculo = "ABC-123",
                            Telefono = "987654321"
                        },
                        new
                        {
                            Id = 2,
                            NombreCompleto = "Carlos Ruiz",
                            PlacaVehiculo = "DEF-456",
                            Telefono = "987654322"
                        },
                        new
                        {
                            Id = 3,
                            NombreCompleto = "María Silva",
                            PlacaVehiculo = "GHI-789",
                            Telefono = "987654323"
                        },
                        new
                        {
                            Id = 4,
                            NombreCompleto = "Luis Gómez",
                            PlacaVehiculo = "JKL-012",
                            Telefono = "987654324"
                        });
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignacionServicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionServicioId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetalleCarga")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Solicitudes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Cliente 1",
                            Codigo = "SOL-100",
                            DetalleCarga = "Carga comercial #1",
                            Direccion = "Av. Prueba 0",
                            Distrito = "Santa Anita",
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 6, 2, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6127),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "Cliente 2",
                            Codigo = "SOL-101",
                            DetalleCarga = "Carga comercial #2",
                            Direccion = "Av. Prueba 10",
                            Distrito = "Comas",
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 6, 1, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6136),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 3,
                            Cliente = "Cliente 3",
                            Codigo = "SOL-102",
                            DetalleCarga = "Carga comercial #3",
                            Direccion = "Av. Prueba 20",
                            Distrito = "El Agustino",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 5, 31, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6139),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 4,
                            Cliente = "Cliente 4",
                            Codigo = "SOL-103",
                            DetalleCarga = "Carga comercial #4",
                            Direccion = "Av. Prueba 30",
                            Distrito = "Callao",
                            Estado = 2,
                            FechaCreacion = new DateTime(2026, 5, 30, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6141),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 5,
                            Cliente = "Cliente 5",
                            Codigo = "SOL-104",
                            DetalleCarga = "Carga comercial #5",
                            Direccion = "Av. Prueba 40",
                            Distrito = "Santa Anita",
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 29, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6144),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 6,
                            Cliente = "Cliente 6",
                            Codigo = "SOL-105",
                            DetalleCarga = "Carga comercial #6",
                            Direccion = "Av. Prueba 50",
                            Distrito = "Comas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 5, 28, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6147),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 7,
                            Cliente = "Cliente 7",
                            Codigo = "SOL-106",
                            DetalleCarga = "Carga comercial #7",
                            Direccion = "Av. Prueba 60",
                            Distrito = "El Agustino",
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 27, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6149),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 8,
                            Cliente = "Cliente 8",
                            Codigo = "SOL-107",
                            DetalleCarga = "Carga comercial #8",
                            Direccion = "Av. Prueba 70",
                            Distrito = "Callao",
                            Estado = 2,
                            FechaCreacion = new DateTime(2026, 5, 26, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6152),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 9,
                            Cliente = "Cliente 9",
                            Codigo = "SOL-108",
                            DetalleCarga = "Carga comercial #9",
                            Direccion = "Av. Prueba 80",
                            Distrito = "Santa Anita",
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 5, 25, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6155),
                            PrecioTotal = 0m
                        },
                        new
                        {
                            Id = 10,
                            Cliente = "Cliente 10",
                            Codigo = "SOL-109",
                            DetalleCarga = "Carga comercial #10",
                            Direccion = "Av. Prueba 90",
                            Distrito = "Comas",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 5, 24, 22, 16, 3, 664, DateTimeKind.Utc).AddTicks(6157),
                            PrecioTotal = 0m
                        });
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.SolicitudProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tamano")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.ToTable("SolicitudProductos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            SolicitudId = 1,
                            Subtotal = 3m,
                            Tamano = 0
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 2,
                            SolicitudId = 2,
                            Subtotal = 12m,
                            Tamano = 1
                        },
                        new
                        {
                            Id = 3,
                            Cantidad = 3,
                            SolicitudId = 3,
                            Subtotal = 30m,
                            Tamano = 2
                        },
                        new
                        {
                            Id = 4,
                            Cantidad = 4,
                            SolicitudId = 4,
                            Subtotal = 12m,
                            Tamano = 0
                        },
                        new
                        {
                            Id = 5,
                            Cantidad = 5,
                            SolicitudId = 5,
                            Subtotal = 30m,
                            Tamano = 1
                        },
                        new
                        {
                            Id = 6,
                            Cantidad = 1,
                            SolicitudId = 6,
                            Subtotal = 10m,
                            Tamano = 2
                        },
                        new
                        {
                            Id = 7,
                            Cantidad = 2,
                            SolicitudId = 7,
                            Subtotal = 6m,
                            Tamano = 0
                        },
                        new
                        {
                            Id = 8,
                            Cantidad = 3,
                            SolicitudId = 8,
                            Subtotal = 18m,
                            Tamano = 1
                        },
                        new
                        {
                            Id = 9,
                            Cantidad = 4,
                            SolicitudId = 9,
                            Subtotal = 40m,
                            Tamano = 2
                        },
                        new
                        {
                            Id = 10,
                            Cantidad = 5,
                            SolicitudId = 10,
                            Subtotal = 15m,
                            Tamano = 0
                        },
                        new
                        {
                            Id = 11,
                            Cantidad = 2,
                            SolicitudId = 1,
                            Subtotal = 20m,
                            Tamano = 2
                        },
                        new
                        {
                            Id = 12,
                            Cantidad = 2,
                            SolicitudId = 2,
                            Subtotal = 20m,
                            Tamano = 2
                        },
                        new
                        {
                            Id = 13,
                            Cantidad = 2,
                            SolicitudId = 3,
                            Subtotal = 20m,
                            Tamano = 2
                        },
                        new
                        {
                            Id = 14,
                            Cantidad = 2,
                            SolicitudId = 4,
                            Subtotal = 20m,
                            Tamano = 2
                        },
                        new
                        {
                            Id = 15,
                            Cantidad = 2,
                            SolicitudId = 5,
                            Subtotal = 20m,
                            Tamano = 2
                        });
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.AsignacionServicio", b =>
                {
                    b.HasOne("Delyport.Api.Models.Entities.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId");

                    b.Navigation("Conductor");
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.HistorialEstado", b =>
                {
                    b.HasOne("Delyport.Api.Models.Entities.AsignacionServicio", "AsignacionServicio")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("AsignacionServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionServicio");
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.SolicitudProducto", b =>
                {
                    b.HasOne("Delyport.Api.Models.Entities.Solicitud", "Solicitud")
                        .WithMany("Productos")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.AsignacionServicio", b =>
                {
                    b.Navigation("HistorialEstados");
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.Solicitud", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
