// <auto-generated />
using System;
using Delyport.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Delyport.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Delyport.Api.Models.Entities.AsignacionServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AsignacionesServicio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoServicio = "SRV-001",
                            Descripcion = "Entrega de contenedor 40ft (Electrónicos)",
                            Destino = "Almacén Central Delyport (San Isidro)",
                            Estado = 0,
                            FechaAsignacion = new DateTime(2026, 6, 2, 18, 49, 50, 188, DateTimeKind.Utc).AddTicks(42),
                            Origen = "Puerto del Callao",
                            Tarifa = 1500.00m
                        },
                        new
                        {
                            Id = 2,
                            CodigoServicio = "SRV-002",
                            Descripcion = "Traslado de repuestos automotrices",
                            Destino = "Taller Delyport (Surquillo)",
                            Estado = 0,
                            FechaAsignacion = new DateTime(2026, 6, 2, 18, 49, 50, 188, DateTimeKind.Utc).AddTicks(46),
                            Origen = "Puerto del Callao",
                            Tarifa = 850.50m
                        });
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.HistorialEstado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AsignacionServicioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionServicioId");

                    b.ToTable("HistorialEstados");
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DetalleCarga")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Solicitudes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cliente = "Importaciones XYZ",
                            Codigo = "SOL-100",
                            DetalleCarga = "10 Cajas de Teclados Mecánicos",
                            Estado = 0,
                            FechaCreacion = new DateTime(2026, 6, 2, 18, 49, 50, 188, DateTimeKind.Utc).AddTicks(138),
                            PesoKg = 150.5m
                        },
                        new
                        {
                            Id = 2,
                            Cliente = "Comercial Alfa",
                            Codigo = "SOL-101",
                            DetalleCarga = "Repuestos de maquinaria agrícola",
                            Estado = 1,
                            FechaCreacion = new DateTime(2026, 6, 1, 18, 49, 50, 188, DateTimeKind.Utc).AddTicks(141),
                            PesoKg = 850.0m
                        });
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.HistorialEstado", b =>
                {
                    b.HasOne("Delyport.Api.Models.Entities.AsignacionServicio", "AsignacionServicio")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("AsignacionServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignacionServicio");
                });

            modelBuilder.Entity("Delyport.Api.Models.Entities.AsignacionServicio", b =>
                {
                    b.Navigation("HistorialEstados");
                });
#pragma warning restore 612, 618
        }
    }
}
